#!/usr/bin/env bash
# This script displays the IP address and HTTP status code from Ap

logfile="$1"

if [[ -z "$logfile" ]]; then
    echo "Usage: $0 <logfile>"
    exit 1
fi

awk '{print $1, $9}' "$logfile"

