#!/usr/bin/env bash
# This script displays the IP address and HTTP status code from Apache logs

awk '{print $1, $9}' apache-access.log
wget https://raw.githubusercontent.com/holbertonschool/0x02-shell_redirections/master/apache-access.log

