#!/usr/bin/env bash
# This script displays numbers from 1 to 20
# For specific numbers, it adds cultural "bad luck" messages

number=1

while [ $number -le 20 ]
do
  echo "$number"
  case $number in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  number=$((number + 1))
done

